# Generated by Django 4.0.2 on 2022-03-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
