# Generated by Django 4.0.2 on 2022-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_article_delete_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guid',
            field=models.URLField(null=True),
        ),
    ]
