# Generated by Django 4.0.2 on 2022-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_article_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.CharField(max_length=50),
        ),
    ]
