# Generated by Django 4.0.2 on 2022-03-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_article_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='NY Times', max_length=100),
        ),
    ]
