# Generated by Django 4.0.2 on 2022-03-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_contact_alter_article_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
