# Generated by Django 4.0.4 on 2022-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
